"""Initial migration

Revision ID: 7fd910f95bf8
Revises: 
Create Date: 2026-01-07 14:54:00.556929

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7fd910f95bf8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('StudentPassword', sa.Text(), nullable=False))
        batch_op.drop_column('StudengtPassword')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('StudengtPassword', mysql.TEXT(charset='utf8mb3', collation='utf8mb3_unicode_ci'), nullable=False))
        batch_op.drop_column('StudentPassword')

    # ### end Alembic commands ###
