"""empty message

Revision ID: 9c9684755740
Revises: fa902cd23557
Create Date: 2019-06-02 21:59:58.583429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c9684755740'
down_revision = 'fa902cd23557'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('CourseCapacity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'CourseCapacity')
    # ### end Alembic commands ###
