"""empty message

Revision ID: bed2de2b203b
Revises: 9c9684755740
Create Date: 2019-06-03 14:48:51.883105

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bed2de2b203b'
down_revision = '9c9684755740'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'course_select_table', 'teacher', ['TeacherNum'], ['TeacherNum'])
    op.drop_constraint('teacher_ibfk_1', 'teacher', type_='foreignkey')
    op.drop_column('teacher', 'CourseNum')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('CourseNum', mysql.VARCHAR(length=8), nullable=True))
    op.create_foreign_key('teacher_ibfk_1', 'teacher', 'course', ['CourseNum'], ['CourseNum'])
    op.add_column('course_select_table', sa.Column('CourseNum', mysql.VARCHAR(length=10), nullable=False))
    op.drop_constraint(None, 'course_select_table', type_='foreignkey')
    # ### end Alembic commands ###
