"""empty message

Revision ID: eb799ea51e5f
Revises: bed2de2b203b
Create Date: 2019-06-03 14:57:41.644715

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eb799ea51e5f'
down_revision = 'bed2de2b203b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'course_select_table', 'course', ['CourseNum'], ['CourseNum'])
    op.drop_index('StudentNum_2', table_name='student')
    op.drop_index('StudentNum_3', table_name='student')
    op.drop_index('TeacherNum_2', table_name='teacher')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('TeacherNum_2', 'teacher', ['TeacherNum'], unique=False)
    op.create_index('StudentNum_3', 'student', ['StudentNum'], unique=False)
    op.create_index('StudentNum_2', 'student', ['StudentNum'], unique=False)
    op.add_column('course_select_table', sa.Column('grade', mysql.INTEGER(display_width=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'course_select_table', type_='foreignkey')
    op.drop_column('course_select_table', 'Grade')
    op.drop_column('course_select_table', 'CourseNum')
    # ### end Alembic commands ###
